// Datenbasis aus "Datenbank.txt"
// Spalten: Saugmedium, Sauger, Bemerkungen Sauger, Vorabscheider,
//          Bemerkungen Vorabscheider, Branche

window.CASES = [
  {
    id: 1,
    saugmedium: "Späne/Emulsion",
    sauger: "Ruwac R10 (SpS35)",
    bemerkungSauger: "mit und ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Spänesauger/Ruwac SPS 35/Ruwac Spänesauger SPS 35 neu.pdf",
    preislisteLinkVorabscheider: "",
    link: "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r10",
  },
  {
    id: 2,
    saugmedium: "Späne/Emulsion",
    sauger: "Ruwac R11 A024 (SpS250)",
    bemerkungSauger: "mit und ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Spänesauger/Ruwac SPS 250/Ruwac Spänesauger SPS250.pdf",
    preislisteLinkVorabscheider: "",
    link: "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r11-a024",
  },
  {
    id: 3,
    saugmedium: "Späne/Emulsion",
    sauger: "Ruwac R11 A036 (SpS250)",
    bemerkungSauger: "mit und ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Spänesauger/Ruwac SPS 250/Ruwac Spänesauger SPS250.pdf",
    preislisteLinkVorabscheider: "",
    link: "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r11-a036",
  },
  {
    id: 4,
    saugmedium: "Späne/Emulsion",
    sauger: "Ruwac R11 R075 (SpS250)",
    bemerkungSauger: "mit und ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Spänesauger/Ruwac SPS 250/Ruwac Spänesauger SPS250.pdf",
    preislisteLinkVorabscheider: "",
    link: "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r11-r075",
  },
  {
    id: 5,
    saugmedium: "Späne/Emulsion",
    sauger: "Ruwac R11 S030 (SpS250)",
    bemerkungSauger: "mit und ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Spänesauger/Ruwac SPS 250 DA30 3kW Z22/Ruwac SPS 250 DA30 3kW Z22.pdf",
    preislisteLinkVorabscheider: "",
    link: "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r11-s030",
  },
  {
    id: 6,
    saugmedium: "Späne/Emulsion",
    sauger: "Delfin TC100MPI",
    bemerkungSauger: "mit Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "Anfrage ST",
    preislisteLink: "",
    preislisteLinkVorabscheider: "",
    link: "",
  },
  {
    id: 7,
    saugmedium: "Späne/Emulsion",
    sauger: "Delfin MTL802 Oil",
    bemerkungSauger: "ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "Anfrage ST",
    preislisteLink: "",
    preislisteLinkVorabscheider: "",
    link: "",
  },
  {
    id: 8,
    saugmedium: "Späne/Emulsion",
    sauger: "Delfin DM40 Oil",
    bemerkungSauger: "ohne Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "Anfrage ST",
    preislisteLink: "",
    preislisteLinkVorabscheider: "",
    link: "",
  },
  {
    id: 9,
    saugmedium: "Späne/Emulsion",
    sauger: "Delfin Tecnoil TC220",
    bemerkungSauger: "mit Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "Anfrage ST",
    preislisteLink: "",
    preislisteLinkVorabscheider: "",
    link: "",
  },
  {
    id: 10,
    saugmedium: "Wasser",
    sauger: "Ruwac WSP2000",
    bemerkungSauger: "mit Pumpe",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Feuerwehren",
    preisliste: "",
    preislisteLink: "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Spänesauger/Ruwac%20WSP%202000/Ruwac%20WSP%202000%20Feuerwehr.pdf",
    preislisteLinkVorabscheider: "",
    link: "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-wsp-2000",
  },
  {
    id: 11,
    saugmedium: "Asche",
    sauger: "Ruwac R01 A024 (WS2220)",
    bemerkungSauger: "",
    vorabscheider: "110L",
    bemerkungVorabscheider: "MTA-V mit Funkensieb",
    branche: "Heizwerke",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Wechselstrom/WS(Z)2220 (Z22)/WS(Z)2220 Zone 22.pdf",
    preislisteLinkVorabscheider:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Vorabscheider/Vorabscheidersystem 110 Liter.pdf",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r01-a024-ba1-t0120m1-z22",
  },
  {
    id: 12,
    saugmedium: "Asche",
    sauger: "Ruwac R01 R040 (DS1400)",
    bemerkungSauger: "",
    vorabscheider: "110L",
    bemerkungVorabscheider: "MTA-V mit Funkensieb",
    branche: "Heizwerke",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Drehstrom/DS1400/DS1400 Zone.pdf",
    preislisteLinkVorabscheider:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Vorabscheider/Vorabscheidersystem 110 Liter.pdf",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r01-r040-ba1-t",
  },
  {
    id: 13,
    saugmedium: "Asche",
    sauger: "Ruwac R01 R040 (DS1400)",
    bemerkungSauger: "",
    vorabscheider: "200L",
    bemerkungVorabscheider: "MTA-V mit Funkensieb",
    branche: "Heizwerke",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Drehstrom/DS1400/DS1400 Zone.pdf",
    preislisteLinkVorabscheider:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Vorabscheider/Vorabscheidersystem 200 Liter.pdf",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r01-r040-ba1-t",
  },
  {
    id: 14,
    saugmedium: "Asche",
    sauger: "Ruwac R01 R075 (DS1750)",
    bemerkungSauger: "",
    vorabscheider: "200L konisch",
    bemerkungVorabscheider: "MTA-V mit Funkensieb, Austragung automatisch",
    branche: "Heizwerke",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Drehstrom/DS1750/DS1750 Zone 22.pdf",
    preislisteLinkVorabscheider:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Vorabscheider/Vorabscheidersystem 200 Liter konisch.pdf",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-r01-b075-ba1-t",
  },
  {
    id: 15,
    saugmedium: "Aufgewirbelter Aluminiumstaub",
    sauger: "Ruwac NA7-11",
    bemerkungSauger: "",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Naßabscheider/Ruwac Naßabscheider NA 7-11 M/Ruwac NA 7-11 M, Zone 22.pdf",
    preislisteLinkVorabscheider:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Naßabscheider/Ruwac Trockenabscheider R26/Ruwac R26 - Trockenabscheider.pdf",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-na7-11",
  },
  {
    id: 16,
    saugmedium: "Aufgewirbelter Aluminiumstaub",
    sauger: "Ruwac NA7-26",
    bemerkungSauger: "",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "",
    preislisteLink:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Naßabscheider/Ruwac Naßabscheider NA 7-26/Ruwac Naßabscheider NA7-26.pdf",
    preislisteLinkVorabscheider:
      "file:///S:/Vertrieb-RT-ADM/Berichte%20und%20Listen/Preislisten/Industriesauger/Ruwac/2024/Naßabscheider/Ruwac Trockenabscheider R26/Ruwac R26 - Trockenabscheider.pdf",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-na7-26",
  },
  {
    id: 17,
    saugmedium: "Aufgewirbelter Aluminiumstaub",
    sauger: "Ruwac NA35",
    bemerkungSauger: "",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "Anfrage ST",
    preislisteLink: "",
    preislisteLinkVorabscheider: "",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-na35",
  },
  {
    id: 18,
    saugmedium: "Aufgewirbelter Aluminiumstaub",
    sauger: "Vorabscheider NA250",
    bemerkungSauger: "",
    vorabscheider: "",
    bemerkungVorabscheider: "",
    branche: "Metall",
    preisliste: "Anfrage ST",
    preislisteLink: "",
    preislisteLinkVorabscheider: "",
    link:
      "https://www.stangl.at/de/produkte/gewerbe-industrie/industriesauger/ruwac-na-250",
  },
];
